#2 containers with seperate ip addresses and both listening on port 80
#1. proxy (image nginx) - port exposed to host
#2. web (image httpd) - port not exposed to host, but listening on port 80 fr

#when only nginx is runnign you see "Welcome to nginx server"
#we have configured nginx as proxy server/ load balancer (nginx.conf)
#listen 80;
#	location / {
#		proxy_pass         http://web; #web is the dns name of httpd server#
#
#so we see "it works" which is returned by httpd running in another container
#
#docker exec -it httpd bash
#echo $HTTPD_PREFIX
#"/usr/local/apache2"
#cat httpd.conf  | grep -i documentroot
#"/usr/local/apache2/htdocs"
#vi index.html 
#"it works"

version: '3'

services:
  proxy:
    image: nginx:1.13 # this will use the latest version of 1.13.x
    ports:
      - '80:80' # expose 80 on host and sent to 80 in container
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro  #bind mount file  and readonly
  web:
    image: httpd  # this will use httpd:latest
